AllCops:
  Exclude:
    - 'lib/light-service.rb'
    - 'vendor/bundle/**/*'
    - 'gemfiles/vendor/bundle/**/*'
    - 'bin/*'
    - 'light-service.gemspec'

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SignalException:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/TrivialAccessors:
  AllowPredicates: true

Naming/PredicateName:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'spec/**/*.rb'

Layout/TrailingBlankLines:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf
